//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 07:04:46 PM CET 
//


package com.insa.rila.xml.paragraph;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soustitre",
    "pOrPHOTO"
})
@XmlRootElement(name = "SEC")
public class SEC {

    @XmlElement(name = "SOUS-TITRE")
    protected String soustitre;
    @XmlElements({
        @XmlElement(name = "P", required = true, type = P.class),
        @XmlElement(name = "PHOTO", required = true, type = PHOTO.class)
    })
    protected List<Object> pOrPHOTO;

    /**
     * Gets the value of the soustitre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOUSTITRE() {
        return soustitre;
    }

    /**
     * Sets the value of the soustitre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOUSTITRE(String value) {
        this.soustitre = value;
    }

    /**
     * Gets the value of the pOrPHOTO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pOrPHOTO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOrPHOTO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link P }
     * {@link PHOTO }
     * 
     * 
     */
    public List<Object> getPOrPHOTO() {
        if (pOrPHOTO == null) {
            pOrPHOTO = new ArrayList<Object>();
        }
        return this.pOrPHOTO;
    }

}
