//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.04 at 07:04:46 PM CET 
//


package com.insa.rila.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DESCRIPTION }
     * 
     */
    public DESCRIPTION createDESCRIPTION() {
        return new DESCRIPTION();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link ITEM }
     * 
     */
    public ITEM createITEM() {
        return new ITEM();
    }

    /**
     * Create an instance of {@link BALADE }
     * 
     */
    public BALADE createBALADE() {
        return new BALADE();
    }

    /**
     * Create an instance of {@link PRESENTATION }
     * 
     */
    public PRESENTATION createPRESENTATION() {
        return new PRESENTATION();
    }

    /**
     * Create an instance of {@link RECIT }
     * 
     */
    public RECIT createRECIT() {
        return new RECIT();
    }

    /**
     * Create an instance of {@link COMPLEMENTS }
     * 
     */
    public COMPLEMENTS createCOMPLEMENTS() {
        return new COMPLEMENTS();
    }

    /**
     * Create an instance of {@link SEC }
     * 
     */
    public SEC createSEC() {
        return new SEC();
    }

    /**
     * Create an instance of {@link PHOTO }
     * 
     */
    public PHOTO createPHOTO() {
        return new PHOTO();
    }

    /**
     * Create an instance of {@link LISTE }
     * 
     */
    public LISTE createLISTE() {
        return new LISTE();
    }

    /**
     * Create an instance of {@link INFO }
     * 
     */
    public INFO createINFO() {
        return new INFO();
    }

}
